Repository Team-Clody/Clody_iOS, pull requests merged in 2024-09, with the labels that each got.

#84 Feat [#83] test server 반영
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Application/AppDelegate.swift
  Clody_iOS/Clody_iOS/Application/SceneDelegate.swift
  Clody_iOS/Clody_iOS/Global/Manager/AppVersionManager.swift
  Clody_iOS/Clody_iOS/Global/Manager/UserManager.swift
  Clody_iOS/Clody_iOS/Global/Resources/waitingLody.json
  Clody_iOS/Clody_iOS/Network/Base/NetworkProvider.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/AuthModel/LoginRequestDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/AuthModel/RevokeResponseDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/AuthModel/SignUpRequestDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/GetReplyResponseDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/GetWritingTimeDTO.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/LoginViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/NicknameViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Cells/DailyCalendarCollectionViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/AccountView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Models/ReplyDetailModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyDetailViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/ViewController.swift
Labels: 🐼 선우, 🍀 Feat

#86 [Fix/#85] ScreenUtil 정수 버전
  Clody_iOS/Clody_iOS/Global/Utils/ScreenUtils.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Cells/DailyCalendarCollectionViewCell.swift
Labels: 🐼 선우, 🛠️ Fix

#88 Feat [#82] 기능, 디자인 QA 반영 업데이트
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/DiaryNotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NicknameView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NotificationPickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/DatePickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyNavigationBar.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyTextField.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/AccountViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/NotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/AccountView.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/ChangeNicknameBottomSheet.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewModels/ReplyWaitingViewModel.swift
Labels: 🐶 나연, 🍀 Feat, 🛠️ Fix

#89 Fix [#87] writing diary 관련 QA 반영
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Application/AppDelegate.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/cancel.imageset/ic_smallx.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/cancel.imageset/ic_smallx@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/cancel.imageset/ic_smallx@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/info.imageset/ic_ Info.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/info.imageset/ic_ Info@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/info.imageset/ic_ Info@3x.png
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryCell.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Views/WritingDiaryView.swift
Labels: 🐼 선우, 🛠️ Fix
