Repository Team-Clody/Clody_iOS, pull requests merged in 2024-07, with the labels that each got.

#4 Set [#3] 폰트, 컬러 세팅
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Extensions/UIFont+.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/blueCustom.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/darkGreen.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/darkYellow.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/grey01.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/grey02.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/grey03.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/grey04.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/grey05.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/grey06.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/grey07.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/grey08.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/lightBlue.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/lightGreen.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/lightYellow.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/mainGreen.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/mainYellow.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/redCustom.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/whiteCustom.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Font/Pretendard-Medium.otf
  Clody_iOS/Clody_iOS/Global/Resources/Font/Pretendard-SemiBold.otf
  Clody_iOS/Clody_iOS/Info.plist
Labels: 🐱 서영, ⚙️ Set

#6 Set [#5] 프로젝트 권한 & 라이브러리 추가
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Clody_iOS.entitlements
  Clody_iOS/Clody_iOS/Info.plist
Labels: 🐼 선우, ⚙️ Set

#8 [Set] Issue Template 수정사항 반영
  .github/ISSUE_TEMPLATE/🐱-issue-template.md
  .github/ISSUE_TEMPLATE/🐶-issue-template.md
  .github/ISSUE_TEMPLATE/🐼-issue-template.md
Labels: 🐶 나연, ⚙️ Set

#11 Set [#10] Font Asset 추가 및 폴더링
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Extensions/UIFont+.swift
  Clody_iOS/Clody_iOS/Global/Resources/Font/Pretendard-Regular.otf
  Clody_iOS/Clody_iOS/Info.plist
  Clody_iOS/Clody_iOS/Presentation/Common/Base/.gitkeep
  Clody_iOS/Clody_iOS/Presentation/Common/Base/BaseView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/.gitkeep
Labels: 🐱 서영, 🖌️ Style, ⚙️ Set

#15 Feat [#9] 공통 컴포넌트 UI 구현
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Extensions/UIFont+.swift
  Clody_iOS/Clody_iOS/Global/Extensions/UIView+.swift
  Clody_iOS/Clody_iOS/Global/Extensions/UIViewController+.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyAlert.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyBottomButton.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyNavigationBar.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyPickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyTextField.swift
  Clody_iOS/Clody_iOS/ViewController.swift
Labels: 🐶 나연, 🍀 Feat, 🖌️ Style

#18 Feat [#12] 설정 & 프로필 및 계정관리 뷰 구현
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/clover 1.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/clover 2.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/clover.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/profile 1.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/profile 2.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/profile.png
  Clody_iOS/Clody_iOS/Presentation/Account/ViewControllers/AccountViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Account/ViewModels/AccountViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Account/Views/AccountView.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Cells/MyPageTableViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/MyPageView.swift
Labels: 🐱 서영, 🍀 Feat

#23 Feat [#17] 일기 작성 화면 UI & 기초 로직 구현
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Application/SceneDelegate.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/addButton.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/addButton.imageset/ic_plus.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/addButton.imageset/ic_plus@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/addButton.imageset/ic_plus@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/addButtonOff.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/addButtonOff.imageset/ic_plusoff.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/addButtonOff.imageset/ic_plusoff@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/addButtonOff.imageset/ic_plusoff@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/cancel.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/cancel.imageset/ic_smallx.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/cancel.imageset/ic_smallx@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/cancel.imageset/ic_smallx@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/helpMessage.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/helpMessage.imageset/Union.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/helpMessage.imageset/Union@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/helpMessage.imageset/Union@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/info.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/info.imageset/ic_ Info.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/info.imageset/ic_ Info@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/info.imageset/ic_ Info@3x.png
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewModels/ListViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/List/Views/ListView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryCell.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Models/WritingDiaryModel.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Views/WritingDiaryView.swift
Labels: 🐼 선우, 🍀 Feat, 🖌️ Style

#25 Feat [#22] 일기 답장 화면 UI 구현
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Extensions/UIFont+.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_four_leaf_clover.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_four_leaf_clover.imageset/img_four_leaf_clover.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_reply_arrived.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_reply_arrived.imageset/img_reply_arrived.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_reply_rody.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_reply_rody.imageset/img_reply_clover.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_writing_reply.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_writing_reply.imageset/img_writing_reply.svg
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/DiaryNotificationView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NicknameView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/OnBoardingView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/TermsView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyBottomButton.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/GetCloverAlertView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Models/ReplyDetailModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyDetailViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewModels/ReplyDetailViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewModels/ReplyWaitingViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyDetailView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyWaitingView.swift
Labels: 🐶 나연, 🍀 Feat, 🖌️ Style

#28 Feat [#24] 삭제하기, 토스트, 네비게이션 연결, 피커뷰 추가
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Application/SceneDelegate.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/toastAlert.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/toastAlert.imageset/Group 37.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/toastAlert.imageset/Group 37@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/toastAlert.imageset/Group 37@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/trash.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/trash.imageset/ic_trash.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/trash.imageset/ic_trash@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/trash.imageset/ic_trash@3x.png
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/DatePickeView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/DeleteBottomSheetView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToast.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToastView.swift
  Clody_iOS/Clody_iOS/Presentation/List/Cells/ListHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewModels/ListViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/List/Views/ListView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
Labels: 🐼 선우, 🍀 Feat, 🖌️ Style

#30 Set [#29] 네트워크 기본 세팅
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Application/AppDelegate.swift
  Clody_iOS/Clody_iOS/Application/SceneDelegate.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/AppICon.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Clody_iOS/Clody_iOS/Info.plist
  Clody_iOS/Clody_iOS/Network/Base/AuthIntercepter.swift
  Clody_iOS/Clody_iOS/Network/Base/BaseModel.swift
  Clody_iOS/Clody_iOS/Network/Base/BaseTargetType.swift
  Clody_iOS/Clody_iOS/Network/Base/NetworkProvider.swift
  Clody_iOS/Clody_iOS/Network/Environment/APIConstant.swift
  Clody_iOS/Clody_iOS/Network/Environment/Config.swift
  Clody_iOS/Clody_iOS/Network/Environment/MoyaPluggin.swift
  Clody_iOS/Clody_iOS/Network/Environment/NetworkHelper.swift
  Clody_iOS/Clody_iOS/Network/Environment/NetworkRequest.swift
  Clody_iOS/Clody_iOS/Network/Environment/NetworkResult.swift
  Clody_iOS/Clody_iOS/Network/MoyaTarget/EmptyResponseDTO.swift
  Clody_iOS/Clody_iOS/Network/MoyaTarget/Providers.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/AuthModel/SignUpRequestDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/AuthModel/SignUpResponseDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/CalendarModel/CalendarRequestDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/AuthRouter.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/CalendarRouter.swift
Labels: 🐼 선우, ⚙️ Set, 📡 Network

#32 Feat [#26] 로그인/회원가입 RxSwift 바인딩 및 화면 연결
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Application/SceneDelegate.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/DiaryNotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/LoginViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/NicknameViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/OnBoardingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/TermsViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModel/DiaryNotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModel/LoginViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModel/NicknameViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModel/OnBoardingViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModel/TermsViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NicknameView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/TermsView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyTextField.swift
Labels: 🐶 나연, 🍀 Feat, 🖌️ Style

#33 [Feat/#31] 키체인 UserManager 구현
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Manager/UserManager.swift
Labels: 🐼 선우, 🍀 Feat

#38 Feat [#37] 캘린더, 리스트 로직 구현
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Extensions/Date+.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover0.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover0.imageset/Group 2085664794.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover0.imageset/Group 2085664794@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover0.imageset/Group 2085664794@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverToday.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverToday.imageset/btn_clover.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverToday.imageset/btn_clover@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverToday.imageset/btn_clover@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverTodayDone.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverTodayDone.imageset/ic_todayclover_yet.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverTodayDone.imageset/ic_todayclover_yet@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverTodayDone.imageset/ic_todayclover_yet@3x.png
  Clody_iOS/Clody_iOS/Network/Service/DTO/CalendarModel/CalendarListResponseDTO.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Cells/CalendarDateCell.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
  Clody_iOS/Clody_iOS/Presentation/List/Cells/ListHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewModels/ListViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
Labels: 🐼 선우, 📡 Network

#40 Network [#34] Auth API 연결
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Application/AppDelegate.swift
  Clody_iOS/Clody_iOS/Application/SceneDelegate.swift
  Clody_iOS/Clody_iOS/Global/Extensions/UIViewController+.swift
  Clody_iOS/Clody_iOS/Global/Manager/UserManager.swift
  Clody_iOS/Clody_iOS/Network/Base/AuthIntercepter.swift
  Clody_iOS/Clody_iOS/Network/Environment/APIConstant.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/MyPageModel/PostSignUpAlarmRequestDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/AuthRouter.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/MyPageRouter.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/DiaryNotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/LoginViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/NicknameViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModel/DiaryNotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModel/LoginViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/DiaryNotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/LoginViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/NicknameViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/OnBoardingViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/TermsViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/DiaryNotificationView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyAlert.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/AccountViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewModels/AccountViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyWaitingView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
Labels: 🐶 나연, 📡 Network

#43 Network [#41] 일기 답장 조회 API 연결 준비
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/GetReplyResponseDTO.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyDetailViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewModels/ReplyWaitingViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyDetailView.swift
Labels: 🐶 나연, 📡 Network

#42 Feat [#39] 키보드 올라가게 추가
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Views/WritingDiaryView.swift
Labels: 🐼 선우, 🖌️ Style

#46 Fix [#41] 일기 저장, 삭제 alert 수정 및 네트워크 헤더 변경
  Clody_iOS/Clody_iOS/Network/Environment/APIConstant.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/AuthRouter.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/CalendarRouter.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/DiaryRouter.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/MyPageRouter.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
Labels: 🐶 나연, 📡 Network

#47 Feat [#44] waiting reply 이니셜라이저 네비게이션 연결
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/DatePickeView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/DeleteBottomSheetView.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
Labels: 🐼 선우, 🍀 Feat

#48 Network/#45 my page
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Application/SceneDelegate.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/ic_kakao 1.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/ic_kakao 2.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/ic_kakao.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/profile 1.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/profile 2.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/profile.png
  Clody_iOS/Clody_iOS/Network/Service/DTO/MyPageModel/GetAlarmResponseDTO.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Cells/NotificationCell.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/AccountViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/NotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewModels/AccountViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewModels/NotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/AccountView.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/NotificationView.swift
Labels: 🐱 서영, 📡 Network

#50 Feat [#50] PermissionManager 설정
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Application/AppDelegate.swift
  Clody_iOS/Clody_iOS/Global/Manager/PermissionManager.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/ic_next.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/ic_next.imageset/ic_next.svg
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/DiaryNotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
  Clody_iOS/Clody_iOS/Presentation/List/Views/ListView.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Cells/MyPageTableViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Cells/NotificationCell.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/NotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/MyPageView.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/NotificationView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyDetailViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
Labels: 🐼 선우, 🍀 Feat

#52 Network [#41] 일기 작성 시간 조회 API 연결 및 전체적인 뷰 개선
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Extensions/Date+.swift
  Clody_iOS/Clody_iOS/Network/Base/AuthIntercepter.swift
  Clody_iOS/Clody_iOS/Network/Environment/MoyaPlugin.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/GetWritingTimeDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/AuthRouter.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/DiaryRouter.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/NicknameViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/TermsViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/DiaryNotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/LoginViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/NicknameViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/TermsViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NicknameView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/TermsView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyPickerView.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyDetailViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewModels/ReplyDetailViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewModels/ReplyWaitingViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyDetailView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyWaitingView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
Labels: 🐶 나연, 🍀 Feat, 📡 Network

#53 Fix [#51] 캘린더 리로딩 및 이슈 수정
  Clody_iOS/Clody_iOS/Global/Extensions/DateFormatter+.swift
  Clody_iOS/Clody_iOS/Network/Base/AuthIntercepter.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Cells/CalendarDateCell.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
  Clody_iOS/Clody_iOS/Presentation/List/Cells/ListHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewModels/ListViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/List/Views/ListView.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/NotificationBottomSheetView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryCell.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryHeaderView.swift
Labels: 🐼 선우, 🍀 Feat

#57 Fix [#55] QA 반영
  Clody_iOS/Clody_iOS/Global/Extensions/DateFormatter+.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/DiaryNotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/NicknameViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NotificationPickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyPickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyTextField.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToast.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToastView.swift
  Clody_iOS/Clody_iOS/Presentation/List/Cells/ListCollectionViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/List/Cells/ListHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewModels/ListViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/AccountViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/NotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewModels/NotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/NotificationBottomSheetView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyDetailView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
Labels: 🐼 선우, 🛠️ Fix
