Repository Team-Clody/Clody_iOS, pull requests merged in 2024-08, with the labels that each got.

#62 Feat [#61] 온보딩 뷰 디테일 작업 짧은 PR
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Application/SceneDelegate.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/darkYellow.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/lightYellow.colorset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Color/mainYellow.colorset/Contents.json
  Clody_iOS/Clody_iOS/Info.plist
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
Labels: 🐶 나연, 🍀 Feat, 🛠️ Fix

#63 Fix [#60] 캘린더 리스트간 년, 월 연동, 불필요한 부분 수정
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Resources/waitingLody.json
  Clody_iOS/Clody_iOS/Presentation/Calendar/Cells/CalendarDateCell.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Cells/DailyCalendarCollectionViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewModels/ListViewModel.swift
Labels: 🐼 선우, 🛠️ Fix

#65 Feat [#64] emptyView 추가 ,isDeleted 값 통해 비활성화 버튼
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Network/Base/NetworkProvider.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/CalendarModel/CalendarListResponseDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/CalendarModel/CalendarMonthlyResponseDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/GetDiaryResponseDTO.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/List/Cells/ListHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/List/Views/ListEmptyView.swift
  Clody_iOS/Clody_iOS/Presentation/List/Views/ListView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Views/WritingDiaryView.swift
Labels: 🐼 선우, 🍀 Feat

#67 Newtwork [#66] network 통신 에러 처리 및 팝업 구현
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Component/ic_ Info.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Component/ic_ Info.imageset/ic_ Info.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Component/ic_ Info.imageset/ic_ Info@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Component/ic_ Info.imageset/ic_ Info@3x.png
  Clody_iOS/Clody_iOS/Network/Base/NetworkProvider.swift
  Clody_iOS/Clody_iOS/Network/Environment/NetworkResult.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyErrorAlertView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Views/WritingDiaryView.swift
Labels: 🐼 선우, 🍀 Feat, 📡 Network

#69 Feat [#68] 에러 다시시도 화면 구현
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Extensions/UIViewController+.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Component/errorRetry.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Component/errorRetry.imageset/Group 2085665010.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Component/errorRetry.imageset/Group 2085665010@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Component/errorRetry.imageset/Group 2085665010@3x.png
  Clody_iOS/Clody_iOS/Network/Environment/NetworkResult.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyErrorAlertView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyErrorRetryView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
Labels: 🐼 선우, 🍀 Feat, 📡 Network

#75 Feat [#74] 기기 대응 및 QA 반영
  Clody_iOS/Clody_iOS/Global/Extensions/UIViewController+.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/Group 2085664926.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/Group 2085664926@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/Group 2085664926@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/clover 2.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/clover.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/ic_kakao 1.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/ic_kakao 2.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/profile.imageset/ic_kakao.png
  Clody_iOS/Clody_iOS/Network/Base/AuthIntercepter.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/SplashViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/DiaryNotificationView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/EmailView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/LoginView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NicknameView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NotificationPickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/OnBoardingDetailView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/OnBoardingView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/TermsView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Cells/CalendarDateCell.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Cells/DailyCalendarCollectionViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/DatePickeView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/DeleteBottomSheetView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyAlert.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyErrorAlertView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyErrorRetryView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyNavigationBar.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyPickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyTextField.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToast.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToastView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/GetCloverAlertView.swift
  Clody_iOS/Clody_iOS/Presentation/List/Cells/ListCollectionViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/List/Cells/ListHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/List/Views/ListEmptyView.swift
  Clody_iOS/Clody_iOS/Presentation/List/Views/ListView.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Cells/MyPageTableViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/AccountViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/AccountView.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/ChangeNicknameBottomSheet.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/MyPageView.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/NotificationView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyDetailView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyWaitingView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryCell.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Views/WritingDiaryView.swift
Labels: 🐼 선우, 🍀 Feat, 🛠️ Fix

#76 Feat [#73] 온보딩, 설정, 답장 화면 에러대응 및 뷰 디테일 개선
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/arrow.imageset/Arrow_Left_5 1.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/arrow.imageset/Arrow_Left_5 2.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/arrow.imageset/Arrow_Left_5.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/arrow.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/Group 2085664926.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/ic_apple_profile.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/ic_apple_profile.imageset/ic_Apple.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/ic_arrow_right_grey.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/ic_arrow_right_grey.imageset/ic_arrow_right_grey.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/ic_clover.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/ic_clover.imageset/ic_clover.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/ic_kakao_profile.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/ic_kakao_profile.imageset/ic_kakao.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/ic_next.imageset/Contents.json
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/GetWritingTimeDTO.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/DiaryNotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/NicknameViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/DiaryNotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/NicknameViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NotificationPickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/OnBoardingDetailView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyAlert.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyPickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToast.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToastView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/GetCloverAlertView.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Cells/MyPageTableViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Cells/NotificationCell.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/AccountViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/NotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewModels/AccountViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewModels/NotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/AccountView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyDetailViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewModels/ReplyDetailViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewModels/ReplyWaitingViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyDetailView.swift
Labels: 🐶 나연, 🍀 Feat, 📡 Network

#78 [Feat/#77] 네트워크 반영
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/PostDiaryResponseDTO.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
Labels: 🍀 Feat, 📡 Network

#80 Fix [#79] v1.0.0 릴리즈 리젝 사항 반영
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS.xcodeproj/xcshareddata/xcschemes/Clody_iOS.xcscheme
  Clody_iOS/Clody_iOS.xcodeproj/xcshareddata/xcschemes/Clody_iOS_Dev.xcscheme
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Manager/UserManager.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Models/SignUpInfoModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/EmailViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/LoginViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/NicknameViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/TermsViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/EmailViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/LoginViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/NicknameViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/EmailView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NicknameView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyTextField.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/ChangeNicknameBottomSheet.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryCell.swift
Labels: 🐶 나연, 🛠️ Fix

#81 Fix [#79] 캘린더 셀이 제대로 안 뜨는 문제 해결 (아이폰 13 프로 맥스 기종에서 발생)
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/Group 2085664926@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Account/clover.imageset/Group 2085664926@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover0.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover0.imageset/Group 2085664794.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover0.imageset/Group 2085664794@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover0.imageset/Group 2085664794@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover0.imageset/clover0.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover1.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover1.imageset/Group 2085664795.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover1.imageset/Group 2085664795@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover1.imageset/Group 2085664795@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover1.imageset/clover1.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover2.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover2.imageset/Group 2085664795.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover2.imageset/Group 2085664795@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover2.imageset/Group 2085664795@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover2.imageset/clover2.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover3.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover3.imageset/Group 2085664796.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover3.imageset/Group 2085664796@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover3.imageset/Group 2085664796@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover3.imageset/clover3.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover4.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover4.imageset/Group 2085664796.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover4.imageset/Group 2085664796@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover4.imageset/Group 2085664796@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover4.imageset/clover4.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover5.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover5.imageset/Group 2085664797.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover5.imageset/Group 2085664797@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover5.imageset/Group 2085664797@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/clover5.imageset/clover5.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverToday.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverToday.imageset/btn_clover.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverToday.imageset/btn_clover@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverToday.imageset/btn_clover@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverToday.imageset/cloverToday.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverTodayDone.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverTodayDone.imageset/cloverTodayDone.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverTodayDone.imageset/ic_todayclover_yet.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverTodayDone.imageset/ic_todayclover_yet@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverTodayDone.imageset/ic_todayclover_yet@3x.png
  Clody_iOS/Clody_iOS/Presentation/Calendar/Cells/CalendarDateCell.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
Labels: 🐶 나연, 🛠️ Fix
