Repository Team-Clody/Clody_iOS, pull requests merged in 2025-07, with the labels that each got.

#127 Fix [#126] v1.2.0 버전 QA사항 반영
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
Labels: 🐶 나연, 🛠️ Fix

#129 Fix [#128] 업데이트 Alert를 Firebase Remote Config에서 받아오는 걸로 수정
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Manager/AppVersionManager.swift
Labels: 🐼 선우, 🛠️ Fix

#131 Feat [#130] localization 기초 파일 구축
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Extensions/String+.swift
  Clody_iOS/Clody_iOS/Global/Literals/LocalizationConstant.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Auth/img_slogan.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Auth/img_slogan.imageset/One Journal, One Lucky Day.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Auth/img_slogan.imageset/img_slogan 1.svg
  Clody_iOS/Clody_iOS/Localizable.xcstrings
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
Labels: 🐼 선우, 🍀 Feat

#134 Feat [#133] calendar, list 현지화 도입
  Clody_iOS/Clody_iOS/Global/Extensions/Date+.swift
  Clody_iOS/Clody_iOS/Global/Extensions/String+.swift
  Clody_iOS/Clody_iOS/Global/Literals/LocalizationConstant.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Manager/AppVersionManager.swift
  Clody_iOS/Clody_iOS/Localizable.xcstrings
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/TermsViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/DatePickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/DeleteBottomSheetView.swift
  Clody_iOS/Clody_iOS/Presentation/List/Views/ListEmptyView.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewControllers/SettingViewController.swift
Labels: 🐼 선우, 🍀 Feat

#145 Feat [#139] 회원가입, 온보딩, 설정 화면 영어 현지화
  Clody_iOS/Clody_iOS/Global/Extensions/DateFormatter+.swift
  Clody_iOS/Clody_iOS/Global/Extensions/String+.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Manager/AppVersionManager.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Auth/img_wordmark.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Auth/img_wordmark.imageset/img_wordmark_en.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Auth/img_wordmark.imageset/img_wordmark_ko.svg
  Clody_iOS/Clody_iOS/Localizable.xcstrings
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/DiaryNotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/LoginViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/NicknameViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/OnBoardingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/SplashViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/DiaryNotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/LoginViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/DiaryNotificationView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/LoginView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NicknameView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/NotificationPickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/OnBoardingDetailView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/OnBoardingView.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/Views/TermsView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyAlert.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyLoginButton.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyPickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyTextField.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Cells/NotificationTableViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Cells/SettingTableViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewControllers/AccountViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewControllers/NotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewModels/SettingViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Views/AccountView.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Views/ChangeNicknameBottomSheet.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Views/NotificationView.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Views/SettingView.swift
Labels: 🐶 나연, 🍀 Feat

#148 Feat [#147] alert, 토스트, 에러 텍스트 현지화
  Clody_iOS/Clody_iOS/Global/Extensions/String+.swift
  Clody_iOS/Clody_iOS/Global/Extensions/UIViewController+.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Localizable.xcstrings
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyAlert.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyErrorAlertView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyErrorRetryView.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToast.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
Labels: 🐼 선우, 🍀 Feat

#149 Feat [#143] 답장 대기, 상세 화면, 바텀시트, URL 영어 UI 현지화
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Extensions/DateComponents+.swift
  Clody_iOS/Clody_iOS/Global/Extensions/String+.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Localizable.xcstrings
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/ContinueWritingAlarmBottomSheet.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/GetCloverAlertView.swift
  Clody_iOS/Clody_iOS/Presentation/Maintenance/Views/MaintenanceView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyDetailView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyWaitingView.swift
Labels: 🐶 나연, 🍀 Feat

#150 Fix [#144] 알림 권한 요청 홈화면으로 이동 및 기타 현지화
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Extensions/String+.swift
  Clody_iOS/Clody_iOS/Global/Literals/LocalizationConstant.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Manager/AppVersionManager.swift
  Clody_iOS/Clody_iOS/Global/Manager/PermissionManager.swift
  Clody_iOS/Clody_iOS/Global/Manager/UserManager.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/kebob.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/kebob.imageset/Frame 925.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/kebob.imageset/Frame 925@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/kebob.imageset/Frame 925@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/kebob.imageset/ic_dot.svg
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/DiaryNotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewControllers/NicknameViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyTextField.swift
  Clody_iOS/Clody_iOS/Presentation/List/Cells/ListCollectionViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/List/Cells/ListHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/List/Views/ListView.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewControllers/AccountViewController.swift
Labels: 🐶 나연, 🍀 Feat
