Repository Team-Clody/Clody_iOS, pull requests merged in 2025-06, with the labels that each got.

#113 Feat [#111] 알림설정 화면 이어쓰기 알림 추가 및 UI 리팩토링
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/MyPageModel/GetAlarmResponseDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/MyPageModel/PostAlarmSetRequestDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/MyPageModel/PostAlarmSetResponseDTO.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/DiaryNotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToast.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToastView.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Cells/NotificationTableViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Model/NotificationState.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewControllers/NotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewModels/NotificationViewModel.swift
Labels: 🐶 나연, 🍀 Feat, ♻️ Refactor

#112 Feat [#110] 캘린더 enum 정리, 일기 작성하기 UI
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverDraft.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverDraft.imageset/diaryState=draft_saved.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverDraftExpired.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Image/Calendar/cloverDraftExpired.imageset/diaryState=expired_written.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/bigAddButton.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/bigAddButton.imageset/type=icon-text, state=default, mode=Default.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/bigAddButton.imageset/type=icon-text, state=default, mode=Default@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/bigAddButton.imageset/type=icon-text, state=default, mode=Default@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/bigAddButtonOff.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/bigAddButtonOff.imageset/type=icon-text, state=default, mode=disabled.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/bigAddButtonOff.imageset/type=icon-text, state=default, mode=disabled@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/bigAddButtonOff.imageset/type=icon-text, state=default, mode=disabled@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/smallAddButton.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/smallAddButton.imageset/type=icon-only, state=_short, mode=Default.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/smallAddButton.imageset/type=icon-only, state=_short, mode=Default@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/smallAddButton.imageset/type=icon-only, state=_short, mode=Default@3x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/smallAddButtonOff.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/smallAddButtonOff.imageset/type=icon-only, state=_short, mode=disabled.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/smallAddButtonOff.imageset/type=icon-only, state=_short, mode=disabled@2x.png
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/WritingDiary/smallAddButtonOff.imageset/type=icon-only, state=_short, mode=disabled@3x.png
  Clody_iOS/Clody_iOS/Presentation/Calendar/Cells/CalendarDateCell.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Enums/CalendarCellData.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Enums/CloverType.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Enums/DiaryButtonState.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryCell.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Views/WritingDiaryView.swift
Labels: 🐼 선우, 🍀 Feat

#117 Feat [#111] 이어쓰기 알림설정 바텀시트 UI 구현 및 캘린더 뷰 코드 정리
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Protocols/BottomSheet.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/CalendarView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/ContinueWritingAlarmBottomSheet.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/DatePickerView.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Views/DeleteBottomSheetView.swift
Labels: 🐶 나연, 🍀 Feat, ♻️ Refactor

#119 Feat [#114] In-App Review 인앱리뷰 요청 기능 구현
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Manager/AppStoreReviewManager.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyDetailViewController.swift
Labels: 🐶 나연, 🍀 Feat

#120 Feat [#115] 임시저장 상태 기능 도입
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/GetDraftDiariesResponseDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/PostDiaryDraftResponseDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/PostDiaryResponseDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/PostDraftDiaryRequestDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/DiaryRouter.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Enums/CloverType.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/Enums/DiaryButtonState.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyAlert.swift
  Clody_iOS/Clody_iOS/Presentation/List/Cells/ListHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
Labels: 🐼 선우, 🍀 Feat

#122 Feat [#118] 이어쓰기 알림설정 바텀시트 비즈니스 로직 구현
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Manager/UserManager.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToast.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToastView.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
Labels: 🐶 나연, 🍀 Feat

#123 Refactor [#121] writing diary 부분 리펙토링
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyAlert.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyDetailViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Cells/WritingDiaryCell.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Models/DiaryItem.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Models/DiaryState.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Models/WritingDiaryModel.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/Views/WritingDiaryView.swift
Labels: ♻️ Refactor

#125 Network [#124] 자동 로그인 조건문 변경, 404 에러 대응 및 경고 해결
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS.xcodeproj/xcshareddata/xcschemes/Clody_iOS.xcscheme
  Clody_iOS/Clody_iOS.xcodeproj/xcshareddata/xcschemes/Clody_iOS_Dev.xcscheme
  Clody_iOS/Clody_iOS/Application/AppDelegate.swift
  Clody_iOS/Clody_iOS/Application/SceneDelegate.swift
  Clody_iOS/Clody_iOS/Global/Manager/AppVersionManager.swift
  Clody_iOS/Clody_iOS/Global/Manager/UserManager.swift
  Clody_iOS/Clody_iOS/Network/Base/AuthIntercepter.swift
  Clody_iOS/Clody_iOS/Presentation/Common/Component/ClodyToast.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewModels/ListViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewControllers/AccountViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewModels/AccountViewModel.swift
Labels: 🐶 나연, 📡 Network
