Repository Team-Clody/Clody_iOS, pull requests merged in 2025-03, with the labels that each got.

#99 Feat [#98] amplitude event 추가
  Clody_iOS/Clody_iOS/Application/AppDelegate.swift
  Clody_iOS/Clody_iOS/Presentation/Auth/ViewModels/DiaryNotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewModels/CalendarViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewControllers/ListViewController.swift
  Clody_iOS/Clody_iOS/Presentation/List/ViewModels/ListViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/AccountViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyDetailViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewControllers/WritingDiaryViewController.swift
  Clody_iOS/Clody_iOS/Presentation/WritingDiary/ViewModels/WritingDiaryViewModel.swift
Labels: 🐼 선우, 🍀 Feat

#101 Feat [#97] 광고 보고 빠른 답장 기능 구현
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Application/AppDelegate.swift
  Clody_iOS/Clody_iOS/Application/SceneDelegate.swift
  Clody_iOS/Clody_iOS/Global/Extensions/Date+.swift
  Clody_iOS/Clody_iOS/Global/Extensions/UIViewController+.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/ic_ad.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/ic_ad.imageset/ic_ad.svg
  Clody_iOS/Clody_iOS/Info.plist
  Clody_iOS/Clody_iOS/Network/Base/AuthIntercepter.swift
  Clody_iOS/Clody_iOS/Network/Environment/APIConstant.swift
  Clody_iOS/Clody_iOS/Network/Environment/Config.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/GetWritingTimeResponseDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/DTO/DiaryModel/PostPatchAdRequestDTO.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/AuthRouter.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/CalendarRouter.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/DiaryRouter.swift
  Clody_iOS/Clody_iOS/Network/Service/Router/MyPageRouter.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewModels/ReplyWaitingViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyWaitingView.swift
Labels: 🐶 나연, 🍀 Feat

#103 Fix [#102] 3차 스프린트 QA 반영
  Clody_iOS/Clody_iOS/Presentation/MyPage/Cells/NotificationCell.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
Labels: 🐶 나연, 🛠️ Fix

#104 Refactor [#92] 설정 화면 전반적인 UI 리팩토링
  Clody_iOS/Clody_iOS.xcodeproj/project.pbxproj
  Clody_iOS/Clody_iOS/Global/Extensions/DateFormatter+.swift
  Clody_iOS/Clody_iOS/Global/Literals/String.swift
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_reply_arrived.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_reply_arrived.imageset/img_reply_arrived.svg
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_writing_reply.imageset/Contents.json
  Clody_iOS/Clody_iOS/Global/Resources/Assets.xcassets/Reply/img_writing_reply.imageset/img_writing_reply.svg
  Clody_iOS/Clody_iOS/Network/Base/AuthIntercepter.swift
  Clody_iOS/Clody_iOS/Presentation/Calendar/ViewControllers/CalendarViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Cells/MyPageTableViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Cells/NotificationCell.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/MyPage/Views/MyPageView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewControllers/ReplyWaitingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/ViewModels/ReplyWaitingViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyDetailView.swift
  Clody_iOS/Clody_iOS/Presentation/Reply/Views/ReplyWaitingView.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Cells/NotificationTableViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Cells/SettingSectionHeaderView.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Cells/SettingTableViewCell.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewControllers/AccountViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewControllers/NotificationViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewControllers/SettingViewController.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewModels/AccountViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewModels/NotificationViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/ViewModels/SettingViewModel.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Views/AccountView.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Views/ChangeNicknameBottomSheet.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Views/NotificationView.swift
  Clody_iOS/Clody_iOS/Presentation/Setting/Views/SettingView.swift
Labels: 🐶 나연, 🖌️ Style, 🛠️ Fix, ♻️ Refactor
